require: rubocop-rspec

AllCops:
  Exclude:
    - 'Gemfile'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrations/**/*'
    - 'db/seeds/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IndentHash:
  EnforcedStyle: consistent

Style/SymbolProc:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/**/*'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/views/**/*'
